name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]      # corre con cada push a main
  workflow_dispatch:         # permite correrlo a mano

permissions:
  contents: write            # permite pushear a gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        # Si tu build necesita un secret:
        # env:
        #   GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
